# Generated by Django 4.1.5 on 2023-01-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomapp', '0002_usermodel_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='forget_password_token',
            field=models.CharField(default='vsdfjsd558dsdfsr5rr', max_length=100),
        ),
    ]
